swipe:
  3:
    left:
      sendkey: "LEFTCTRL+PAGEUP"
    right:
      sendkey: "LEFTCTRL+PAGEDOWN"
    up:
      sendkey: "LEFTMETA+Q"
    down:
      sendkey: "LEFTMETA+E"
  4:
    left:
      interval: 1.0
      sendkey: "LEFTALT+LEFT"
    right:
      interval: 1.0
      sendkey: "LEFTALT+RIGHT"
    up:
      sendkey: "LEFTCTRL+W"
      interval: 1.0 
    down:
      sendkey: "LEFTCTRL+R"
      interval: 1.0

pinch:
  3:
    in:
      sendkey: "LEFTALT+D"
    out:
      sendkey: "LEFTCTRL+T"

rotate:
  4:
    clockwise: 
      sendkey: "LEFTCTRL+LEFTSHIFT+T"
    counterclockwise:
      sendkey: "LEFTCTRL+LEFTSHIFT+T"

threshold:
  swipe: 0.05
  pinch: 0.5

interval: 
  swipe: 0.5

