[greenclip]
  blacklisted_applications = []

  static_history = []

  image_cache_directory = "/tmp/greenclip"
  history_file = "/home/shvix/.cache/greenclip.history"

  max_history_length = 250
  max_selection_size_bytes = 0

  enable_image_support = true
  trim_space_from_selection = true
  use_primary_selection_as_input = false
